(part "1206B475K500NT"
    (packageRef "CAPC3216X190N")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "32")
    (property "Manufacturer_Name" "FH(Guangdong Fenghua Advanced Tech)")
    (property "Manufacturer_Part_Number" "1206B475K500NT")
    (property "Mouser_Part_Number" "")
    (property "Mouser_Price/Stock" "")
    (property "Arrow_Part_Number" "")
    (property "Arrow_Price/Stock" "")
    (property "Description" "4.7uF +/-10% 50V X7R 1206 Multilayer Ceramic Capacitors MLCC - SMD/SMT RoHS")
    (property "Datasheet_Link" "https://datasheet.lcsc.com/szlcsc/Guangdong-Fenghua-Advanced-Tech-1206B475K500NT_C29823.pdf")
    (property "symbolName1" "1206B475K500NT")
)
